allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
  - noperm
parameters:
  skuName: Standard_LRS
  location: eastus
  secretNamespace: kube-system
  storageAccount: aroy4fvuxotazurefile
  resourceGroup: aro-y4fvuxot-azure-file
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
